# config.yml
grief:
  mode: "allow_everywhere_except_safe" # или "allow_only_listed"
  safe-regions:
    - spawn
    - market
  safe-worlds:
    - world_nether_safe
  allowed-regions: []   # используешь, если mode = allow_only_listed
features:
  falling_blocks: true
  pistons: true
  wither: true
cleanup:
  falling_block_mark_ms: 1000   # окно, в которое отменяем ItemSpawn после падения блока